CREATE TABLE IF NOT EXISTS sys_health_check (
    id         BIGINT       NOT NULL AUTO_INCREMENT,
    checked_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
